Math: fix missing header
Was causing:
```
In file included from D:/dev/floormat/external/magnum/src/Magnum/Math/Unit.h:33,
                 from D:/dev/floormat/external/magnum/src/Magnum/Math/Time.h:40,
                 from D:/dev/floormat/external/magnum/src/Magnum/Math/Time.cpp:27:
D:/dev/floormat/external/magnum/src/Magnum/Math/TypeTraits.h:493:12: error: 'CORRADE_CONSTEXPR14' does not name a type [-Wtemplate-body]
  493 |     static CORRADE_CONSTEXPR14 bool equals(T a, T b);
      |            ^~~~~~~~~~~~~~~~~~~